name: release

on:
  push:
    branches:
      - master
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i --no-save semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GIT_AUTHOR_NAME: David Jakowenko
          GIT_AUTHOR_EMAIL: jakowenko@gmail.com
          GIT_COMMITTER_NAME: David Jakowenko
          GIT_COMMITTER_EMAIL: jakowenko@gmail.com
        run: npx semantic-release
