name: build test

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install node
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bash
          sudo apt-get install -y gcc g++ make libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev jq unzip wget
          cd api
          npm install --production --ignore-scripts
          cd ../frontend
          npm install
          npm run build
          cd ..
          npm install nodemon -g
          
